[package]
name = "eelf"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["eelf-cli"]

[dependencies]
thiserror = "2"
flagset = "0.4.6"
phf = { version = "0.11", features = ["macros"] }
num-traits = "0.2"
num-derive = "0.4"
